### ISSUE TITLE
Instructions to install it

### ISSUE THREAD

**Issue by msalih2022** [aksharlabs/deepin-uengine-rooted-gaps-image#1]
How do you install this with uengine-runner?

**Comment by aksharlabs** [comment]
You have to replace android image with this one

**Comment by msalih2022** [comment]
> You have to replace android image with this one

I tried to do this but the image won't boot.
![Screenshot_20221022214623](https://user-images.githubusercontent.com/109634790/197359783-c5217367-f084-4fa3-8caf-ed1a62e82c44.png)
![Screenshot_20221022214726](https://user-images.githubusercontent.com/109634790/197359793-22a08d97-c650-40bf-a3b4-ec8e46e51817.png)

What did I do?

- I repacked the original uengine-android-image Debian package with the image you provided instead of the original one.
- Installed the modified package

You can see below that I'm running your image, which weighs more than 800MB, while the original is less than 600MB.
![Screenshot_20221022214748](https://user-images.githubusercontent.com/109634790/197359845-4b0ce3b6-5bcd-4743-874d-52144681d1df.png)

**Comment by aksharlabs** [comment]
Let me check if this image works on recent version of uengine

**Comment by aksharlabs** [comment]
working fine with latest uengine 
![Screenshot_dde-desktop_20221023124204](https://user-images.githubusercontent.com/74598801/197372664-aac690af-102c-494d-b76e-839caa2ea162.png)
![Screenshot_dde-desktop_20221023124355](https://user-images.githubusercontent.com/74598801/197372667-3f32fece-f35e-4d69-bfa1-9d91c294eec3.png)

**Comment by aksharlabs** [comment]
you just have to rename  /usr/share/uengine/.android.img  to .androi.img.bak and copy downloded image then rename  to .android.img. and restart pc. then let me know if working
![Screenshot_dde-file-manager_20221023125037](https://user-images.githubusercontent.com/74598801/197372826-e4506c4f-37e8-4908-b2f7-16eb69b90aa5.png)

**Comment by msalih2022** [comment]
Still does not work.

Anyways, maybe you can show me how you installed libhoudini and gapps on the stock uengine android image, give me a tutorial so I can do it on my own.

**Comment by aksharlabs** [comment]
I got some codes from here. [https://www.linuxuprising.com/2018/07/anbox-how-to-install-google-play-store.html?m=1](https://www.linuxuprising.com/2018/07/anbox-how-to-install-google-play-store.html?m=1)  but this guide is for anbox.  I think there i have installed some libhoudini related dependencys.I will make android image package with those.

**Comment by aksharlabs** [comment]
You may share your social ids to live chat at aksharlabs2[@]gmail.com. this image is working fine on new deepin installation too. Maybe yo didn't do raplace correctly or your download was currupted.
